### PR TITLE
Fixed the modal so that it's keyboard friendly now

### PR DESCRIPTION
**Pull request by Aaron-M-Anderson**

### CODE REVIEW

**Comment by reynoldsnlp** [comment]
@Thanatos55 remind me what still needs to be done on this PR.

**Comment by Thanatos55** [comment]
As far as this one goes, it should be good now because I changed the color
to blue for the outline. Unless there's some other design changes needed it
should be all good to go

**Review by Thanatos55 — COMMENTED** [review]
I finished reviewing all of the files that were edited in this branch and everything looks good to me for a merge into develop!

**Review by ChristianHall131 — APPROVED** [review]
Looks good!

**Pull request merged**
